// Örnek ürün verileri
export const products = [
 // Bilgisayar ve Tablet
 {
  id: 1,
  name: "Apple MacBook Air M3 13\"",
  slug: "macbook-air-m3",
  category: "bilgisayar-tablet",
  price: 54999,
  oldPrice: 59999,
  discount: 8,
  image: "https://picsum.photos/seed/macbook/400/400",
  rating: 4.9,
  reviewCount: 256,
  isNew: true,
  inStock: true,
  specs: ["M3 Chip", "8GB RAM", "256GB SSD"],
 },
 {
  id: 2,
  name: "Samsung Galaxy Tab S9 Ultra",
  slug: "galaxy-tab-s9-ultra",
  category: "bilgisayar-tablet",
  price: 42999,
  oldPrice: 47999,
  discount: 10,
  image: "https://picsum.photos/seed/tablet/400/400",
  rating: 4.7,
  reviewCount: 189,
  isNew: true,
  inStock: true,
  specs: ["14.6\" AMOLED", "12GB RAM", "256GB"],
 },
 {
  id: 3,
  name: "iPad Pro 12.9\" M2",
  slug: "ipad-pro-m2",
  category: "bilgisayar-tablet",
  price: 48999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/ipad/400/400",
  rating: 4.8,
  reviewCount: 342,
  isNew: false,
  inStock: true,
  specs: ["M2 Chip", "8GB RAM", "128GB"],
 },
 {
  id: 4,
  name: "ASUS ROG Zephyrus G14",
  slug: "asus-rog-zephyrus-g14",
  category: "bilgisayar-tablet",
  price: 67999,
  oldPrice: 74999,
  discount: 9,
  image: "https://picsum.photos/seed/laptop/400/400",
  rating: 4.6,
  reviewCount: 128,
  isNew: false,
  inStock: true,
  specs: ["Ryzen 9", "32GB RAM", "RTX 4070"],
 },
 {
  id: 5,
  name: "Lenovo ThinkPad X1 Carbon",
  slug: "thinkpad-x1-carbon",
  category: "bilgisayar-tablet",
  price: 52999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/thinkpad/400/400",
  rating: 4.5,
  reviewCount: 95,
  isNew: false,
  inStock: false,
  specs: ["Intel i7", "16GB RAM", "512GB SSD"],
 },
 {
  id: 6,
  name: "Microsoft Surface Pro 9",
  slug: "surface-pro-9",
  category: "bilgisayar-tablet",
  price: 38999,
  oldPrice: 42999,
  discount: 9,
  image: "https://picsum.photos/seed/surface/400/400",
  rating: 4.4,
  reviewCount: 167,
  isNew: false,
  inStock: true,
  specs: ["Intel i5", "8GB RAM", "256GB SSD"],
 },

 // Kamera
 {
  id: 7,
  name: "Sony Alpha A7 IV",
  slug: "sony-alpha-a7-iv",
  category: "kamera",
  price: 89999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/camera1/400/400",
  rating: 4.9,
  reviewCount: 78,
  isNew: true,
  inStock: true,
  specs: ["33MP", "4K Video", "5-Axis IBIS"],
 },
 {
  id: 8,
  name: "Canon EOS R6 Mark II",
  slug: "canon-eos-r6-mark-ii",
  category: "kamera",
  price: 74999,
  oldPrice: 79999,
  discount: 6,
  image: "https://picsum.photos/seed/camera2/400/400",
  rating: 4.8,
  reviewCount: 92,
  isNew: true,
  inStock: true,
  specs: ["24.2MP", "4K 60fps", "Dual Pixel AF"],
 },
 {
  id: 9,
  name: "Nikon Z8",
  slug: "nikon-z8",
  category: "kamera",
  price: 109999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/camera3/400/400",
  rating: 4.9,
  reviewCount: 45,
  isNew: true,
  inStock: true,
  specs: ["45.7MP", "8K Video", "Pro Build"],
 },
 {
  id: 10,
  name: "Fujifilm X-T5",
  slug: "fujifilm-x-t5",
  category: "kamera",
  price: 59999,
  oldPrice: 64999,
  discount: 8,
  image: "https://picsum.photos/seed/camera4/400/400",
  rating: 4.7,
  reviewCount: 156,
  isNew: false,
  inStock: true,
  specs: ["40MP", "6.2K Video", "Film Sim"],
 },
 {
  id: 11,
  name: "GoPro Hero 12 Black",
  slug: "gopro-hero-12",
  category: "kamera",
  price: 14999,
  oldPrice: 17999,
  discount: 17,
  image: "https://picsum.photos/seed/gopro/400/400",
  rating: 4.6,
  reviewCount: 289,
  isNew: false,
  inStock: true,
  specs: ["5.3K Video", "HyperSmooth 6.0", "Waterproof"],
 },
 {
  id: 12,
  name: "DJI Osmo Pocket 3",
  slug: "dji-osmo-pocket-3",
  category: "kamera",
  price: 19999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/osmo/400/400",
  rating: 4.8,
  reviewCount: 134,
  isNew: true,
  inStock: true,
  specs: ["4K 120fps", "1\" CMOS", "3-Axis Gimbal"],
 },

 // Şarj & Pil
 {
  id: 13,
  name: "Anker PowerCore 26800mAh",
  slug: "anker-powercore-26800",
  category: "sarj-pil",
  price: 1299,
  oldPrice: 1599,
  discount: 19,
  image: "https://picsum.photos/seed/powerbank1/400/400",
  rating: 4.7,
  reviewCount: 567,
  isNew: false,
  inStock: true,
  specs: ["26800mAh", "3 USB Ports", "Fast Charge"],
 },
 {
  id: 14,
  name: "Samsung 45W Hızlı Şarj Adaptörü",
  slug: "samsung-45w-adapter",
  category: "sarj-pil",
  price: 899,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/charger1/400/400",
  rating: 4.5,
  reviewCount: 234,
  isNew: false,
  inStock: true,
  specs: ["45W", "USB-C", "PD 3.0"],
 },
 {
  id: 15,
  name: "Apple MagSafe Şarj Aleti",
  slug: "apple-magsafe-charger",
  category: "sarj-pil",
  price: 1499,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/magsafe/400/400",
  rating: 4.6,
  reviewCount: 189,
  isNew: false,
  inStock: true,
  specs: ["15W Wireless", "MagSafe", "iPhone 12+"],
 },
 {
  id: 16,
  name: "Baseus 65W GaN Şarj Aleti",
  slug: "baseus-65w-gan",
  category: "sarj-pil",
  price: 799,
  oldPrice: 999,
  discount: 20,
  image: "https://picsum.photos/seed/charger2/400/400",
  rating: 4.8,
  reviewCount: 412,
  isNew: true,
  inStock: true,
  specs: ["65W", "GaN Tech", "2x USB-C"],
 },

 // Kulaklık
 {
  id: 17,
  name: "Apple AirPods Pro 2",
  slug: "airpods-pro-2",
  category: "kulaklik",
  price: 8999,
  oldPrice: 9999,
  discount: 10,
  image: "https://picsum.photos/seed/airpods/400/400",
  rating: 4.8,
  reviewCount: 1256,
  isNew: false,
  inStock: true,
  specs: ["ANC", "Adaptive Audio", "USB-C"],
 },
 {
  id: 18,
  name: "Sony WH-1000XM5",
  slug: "sony-wh-1000xm5",
  category: "kulaklik",
  price: 11999,
  oldPrice: 13999,
  discount: 14,
  image: "https://picsum.photos/seed/sony-headphones/400/400",
  rating: 4.9,
  reviewCount: 876,
  isNew: false,
  inStock: true,
  specs: ["Industry-leading ANC", "30H Battery", "Hi-Res"],
 },
 {
  id: 19,
  name: "Bose QuietComfort Ultra",
  slug: "bose-qc-ultra",
  category: "kulaklik",
  price: 13999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/bose/400/400",
  rating: 4.7,
  reviewCount: 234,
  isNew: true,
  inStock: true,
  specs: ["Immersive Audio", "CustomTune", "24H Battery"],
 },
 {
  id: 20,
  name: "Samsung Galaxy Buds2 Pro",
  slug: "galaxy-buds2-pro",
  category: "kulaklik",
  price: 4999,
  oldPrice: 5999,
  discount: 17,
  image: "https://picsum.photos/seed/buds/400/400",
  rating: 4.5,
  reviewCount: 567,
  isNew: false,
  inStock: true,
  specs: ["ANC", "24bit Hi-Fi", "IPX7"],
 },

 // Saat & Akıllı Saat
 {
  id: 21,
  name: "Apple Watch Ultra 2",
  slug: "apple-watch-ultra-2",
  category: "saat-akilli-saat",
  price: 29999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/watch1/400/400",
  rating: 4.9,
  reviewCount: 345,
  isNew: true,
  inStock: true,
  specs: ["49mm", "GPS + Cellular", "Titanium"],
 },
 {
  id: 22,
  name: "Samsung Galaxy Watch 6 Classic",
  slug: "galaxy-watch-6-classic",
  category: "saat-akilli-saat",
  price: 12999,
  oldPrice: 14999,
  discount: 13,
  image: "https://picsum.photos/seed/watch2/400/400",
  rating: 4.6,
  reviewCount: 234,
  isNew: false,
  inStock: true,
  specs: ["47mm", "Rotating Bezel", "WearOS"],
 },
 {
  id: 23,
  name: "Garmin Fenix 7X Solar",
  slug: "garmin-fenix-7x",
  category: "saat-akilli-saat",
  price: 24999,
  oldPrice: 27999,
  discount: 11,
  image: "https://picsum.photos/seed/garmin/400/400",
  rating: 4.8,
  reviewCount: 178,
  isNew: false,
  inStock: true,
  specs: ["Solar", "Multi-Sport", "Topo Maps"],
 },

 // Küçük Ev Aletleri
 {
  id: 24,
  name: "Dyson V15 Detect",
  slug: "dyson-v15-detect",
  category: "kucuk-ev-aletleri",
  price: 27999,
  oldPrice: 31999,
  discount: 13,
  image: "https://picsum.photos/seed/dyson/400/400",
  rating: 4.8,
  reviewCount: 456,
  isNew: false,
  inStock: true,
  specs: ["Laser Detect", "60min Battery", "LCD Screen"],
 },
 {
  id: 25,
  name: "Philips Air Fryer XXL",
  slug: "philips-airfryer-xxl",
  category: "kucuk-ev-aletleri",
  price: 8999,
  oldPrice: 10999,
  discount: 18,
  image: "https://picsum.photos/seed/airfryer/400/400",
  rating: 4.7,
  reviewCount: 789,
  isNew: false,
  inStock: true,
  specs: ["7.3L", "Rapid Air", "Digital"],
 },
 {
  id: 26,
  name: "iRobot Roomba j7+",
  slug: "irobot-roomba-j7",
  category: "kucuk-ev-aletleri",
  price: 19999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/roomba/400/400",
  rating: 4.6,
  reviewCount: 234,
  isNew: true,
  inStock: true,
  specs: ["Self-Empty", "Smart Mapping", "P.O.O.P."],
 },

 // Mutfak
 {
  id: 27,
  name: "KitchenAid Stand Mikser",
  slug: "kitchenaid-stand-mixer",
  category: "mutfak",
  price: 14999,
  oldPrice: 17999,
  discount: 17,
  image: "https://picsum.photos/seed/mixer/400/400",
  rating: 4.9,
  reviewCount: 567,
  isNew: false,
  inStock: true,
  specs: ["4.8L", "300W", "10 Speeds"],
 },
 {
  id: 28,
  name: "Sage Barista Express",
  slug: "sage-barista-express",
  category: "mutfak",
  price: 18999,
  oldPrice: 21999,
  discount: 14,
  image: "https://picsum.photos/seed/espresso/400/400",
  rating: 4.8,
  reviewCount: 345,
  isNew: false,
  inStock: true,
  specs: ["Grinder", "Steam Wand", "PID Control"],
 },
 {
  id: 29,
  name: "Vitamix A3500",
  slug: "vitamix-a3500",
  category: "mutfak",
  price: 22999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/blender/400/400",
  rating: 4.9,
  reviewCount: 189,
  isNew: true,
  inStock: true,
  specs: ["2.2HP", "Touchscreen", "Self-Clean"],
 },

 // El Aletleri
 {
  id: 30,
  name: "Bosch GSR 18V-60 Akülü Matkap",
  slug: "bosch-gsr-18v-60",
  category: "el-aletleri",
  price: 4999,
  oldPrice: 5999,
  discount: 17,
  image: "https://picsum.photos/seed/drill/400/400",
  rating: 4.7,
  reviewCount: 234,
  isNew: false,
  inStock: true,
  specs: ["18V", "60Nm", "Brushless"],
 },
 {
  id: 31,
  name: "Makita DHP486 Darbeli Matkap",
  slug: "makita-dhp486",
  category: "el-aletleri",
  price: 5999,
  oldPrice: null,
  discount: 0,
  image: "https://picsum.photos/seed/makita/400/400",
  rating: 4.8,
  reviewCount: 156,
  isNew: true,
  inStock: true,
  specs: ["18V", "130Nm", "BL Motor"],
 },
 {
  id: 32,
  name: "DeWalt DCS391 Daire Testere",
  slug: "dewalt-dcs391",
  category: "el-aletleri",
  price: 3999,
  oldPrice: 4499,
  discount: 11,
  image: "https://picsum.photos/seed/saw/400/400",
  rating: 4.6,
  reviewCount: 89,
  isNew: false,
  inStock: true,
  specs: ["18V", "165mm", "24T Blade"],
 },
];

// Kategori bilgileri
export const categoryInfo = {
 "bilgisayar-tablet": {
  title: "Bilgisayar ve Tablet",
  description: "En yeni dizüstü bilgisayarlar, tabletler ve aksesuarlar",
  banner: "https://picsum.photos/seed/computers/1200/300",
 },
 "kamera": {
  title: "Kamera",
  description: "Profesyonel fotoğraf makineleri ve video ekipmanları",
  banner: "https://picsum.photos/seed/cameras/1200/300",
 },
 "sarj-pil": {
  title: "Şarj & Pil",
  description: "Powerbank, şarj aletleri ve pil çeşitleri",
  banner: "https://picsum.photos/seed/charging/1200/300",
 },
 "kulaklik": {
  title: "Kulaklık",
  description: "Kablosuz kulaklıklar ve ses sistemleri",
  banner: "https://picsum.photos/seed/headphones/1200/300",
 },
 "saat-akilli-saat": {
  title: "Saat & Giyilebilir",
  description: "Akıllı saatler ve fitness takip cihazları",
  banner: "https://picsum.photos/seed/watches/1200/300",
 },
 "kucuk-ev-aletleri": {
  title: "Küçük Ev Aletleri",
  description: "Elektrikli süpürgeler, temizlik ve bakım ürünleri",
  banner: "https://picsum.photos/seed/appliances/1200/300",
 },
 "mutfak": {
  title: "Mutfak",
  description: "Mutfak robotları, kahve makineleri ve blenderlar",
  banner: "https://picsum.photos/seed/kitchen/1200/300",
 },
 "el-aletleri": {
  title: "El Aletleri",
  description: "Profesyonel ve hobi amaçlı el aletleri",
  banner: "https://picsum.photos/seed/tools/1200/300",
 },
};

export function getProductsByCategory(categorySlug) {
 return products.filter((product) => product.category === categorySlug);
}

export function getProductById(id) {
 return products.find((product) => product.id === id);
}

export function getProductBySlug(slug) {
 return products.find((product) => product.slug === slug);
}

export function getNewProducts() {
 return products.filter((product) => product.isNew);
}

export function getDiscountedProducts() {
 return products.filter((product) => product.discount > 0);
}

export function formatPrice(price) {
 return new Intl.NumberFormat("tr-TR", {
  style: "currency",
  currency: "TRY",
  minimumFractionDigits: 0,
  maximumFractionDigits: 0,
 }).format(price);
}

